name: Build Docker image, Push Docker/Create merge request

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      id: docker_build
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/1114-weather-app
        VERSION=0.0.${{ github.run_number}}
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
        echo "IMAGE=$IMAGE_NAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Push Docker Image (Main Branch Only)
      if: github.ref_name == 'main'
      run: |
        docker push ${{ env.IMAGE }}:latest
        docker push ${{ env.IMAGE }}:${{ env.VERSION }}

    - name: Create Pull Request (Other Branches[not main])
      if: github.ref_name != 'main'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Build docker image for branch ${{ github.ref_name }}"
        title: "Create pull request for branch ${{ github.ref_name }} to main"
        body: |
          This pull request includes the Docker image build for branch ${{ github.ref_name }}.
          Built Versions:
            - `Latest`
            - `${{ env.VERSION }}`
        base: main
        branch: ${{ github.ref_name }}